/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsRouteRouteImport } from './routes/components/route'
import { Route as FoundationsRouteRouteImport } from './routes/foundations/route'
import { Route as ComponentsBeakRouteImport } from './routes/components/beak'
import { Route as ComponentsBubbleRouteImport } from './routes/components/bubble'
import { Route as ComponentsButtonRouteImport } from './routes/components/button'
import { Route as ComponentsNestRouteImport } from './routes/components/nest'
import { Route as ComponentsSelectRouteImport } from './routes/components/select'
import { Route as FoundationsColorsRouteImport } from './routes/foundations/colors'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRouteRoute = ComponentsRouteRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationsRouteRoute = FoundationsRouteRouteImport.update({
  id: '/foundations',
  path: '/foundations',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsBeakRoute = ComponentsBeakRouteImport.update({
  id: '/beak',
  path: '/beak',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsBubbleRoute = ComponentsBubbleRouteImport.update({
  id: '/bubble',
  path: '/bubble',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsButtonRoute = ComponentsButtonRouteImport.update({
  id: '/button',
  path: '/button',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsNestRoute = ComponentsNestRouteImport.update({
  id: '/nest',
  path: '/nest',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsSelectRoute = ComponentsSelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const FoundationsColorsRoute = FoundationsColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => FoundationsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRouteRouteWithChildren
  '/foundations': typeof FoundationsRouteRouteWithChildren
  '/components/beak': typeof ComponentsBeakRoute
  '/components/bubble': typeof ComponentsBubbleRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/nest': typeof ComponentsNestRoute
  '/components/select': typeof ComponentsSelectRoute
  '/foundations/colors': typeof FoundationsColorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRouteRouteWithChildren
  '/foundations': typeof FoundationsRouteRouteWithChildren
  '/components/beak': typeof ComponentsBeakRoute
  '/components/bubble': typeof ComponentsBubbleRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/nest': typeof ComponentsNestRoute
  '/components/select': typeof ComponentsSelectRoute
  '/foundations/colors': typeof FoundationsColorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components': typeof ComponentsRouteRouteWithChildren
  '/foundations': typeof FoundationsRouteRouteWithChildren
  '/components/beak': typeof ComponentsBeakRoute
  '/components/bubble': typeof ComponentsBubbleRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/nest': typeof ComponentsNestRoute
  '/components/select': typeof ComponentsSelectRoute
  '/foundations/colors': typeof FoundationsColorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components'
    | '/foundations'
    | '/components/beak'
    | '/components/bubble'
    | '/components/button'
    | '/components/nest'
    | '/components/select'
    | '/foundations/colors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components'
    | '/foundations'
    | '/components/beak'
    | '/components/bubble'
    | '/components/button'
    | '/components/nest'
    | '/components/select'
    | '/foundations/colors'
  id:
    | '__root__'
    | '/'
    | '/components'
    | '/foundations'
    | '/components/beak'
    | '/components/bubble'
    | '/components/button'
    | '/components/nest'
    | '/components/select'
    | '/foundations/colors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsRouteRoute: typeof ComponentsRouteRouteWithChildren
  FoundationsRouteRoute: typeof FoundationsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundations': {
      id: '/foundations'
      path: '/foundations'
      fullPath: '/foundations'
      preLoaderRoute: typeof FoundationsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/beak': {
      id: '/components/beak'
      path: '/beak'
      fullPath: '/components/beak'
      preLoaderRoute: typeof ComponentsBeakRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/bubble': {
      id: '/components/bubble'
      path: '/bubble'
      fullPath: '/components/bubble'
      preLoaderRoute: typeof ComponentsBubbleRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/button': {
      id: '/components/button'
      path: '/button'
      fullPath: '/components/button'
      preLoaderRoute: typeof ComponentsButtonRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/nest': {
      id: '/components/nest'
      path: '/nest'
      fullPath: '/components/nest'
      preLoaderRoute: typeof ComponentsNestRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/select': {
      id: '/components/select'
      path: '/select'
      fullPath: '/components/select'
      preLoaderRoute: typeof ComponentsSelectRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/foundations/colors': {
      id: '/foundations/colors'
      path: '/colors'
      fullPath: '/foundations/colors'
      preLoaderRoute: typeof FoundationsColorsRouteImport
      parentRoute: typeof FoundationsRouteRoute
    }
  }
}

interface ComponentsRouteRouteChildren {
  ComponentsBeakRoute: typeof ComponentsBeakRoute
  ComponentsBubbleRoute: typeof ComponentsBubbleRoute
  ComponentsButtonRoute: typeof ComponentsButtonRoute
  ComponentsNestRoute: typeof ComponentsNestRoute
  ComponentsSelectRoute: typeof ComponentsSelectRoute
}

const ComponentsRouteRouteChildren: ComponentsRouteRouteChildren = {
  ComponentsBeakRoute: ComponentsBeakRoute,
  ComponentsBubbleRoute: ComponentsBubbleRoute,
  ComponentsButtonRoute: ComponentsButtonRoute,
  ComponentsNestRoute: ComponentsNestRoute,
  ComponentsSelectRoute: ComponentsSelectRoute,
}

const ComponentsRouteRouteWithChildren = ComponentsRouteRoute._addFileChildren(
  ComponentsRouteRouteChildren,
)

interface FoundationsRouteRouteChildren {
  FoundationsColorsRoute: typeof FoundationsColorsRoute
}

const FoundationsRouteRouteChildren: FoundationsRouteRouteChildren = {
  FoundationsColorsRoute: FoundationsColorsRoute,
}

const FoundationsRouteRouteWithChildren =
  FoundationsRouteRoute._addFileChildren(FoundationsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsRouteRoute: ComponentsRouteRouteWithChildren,
  FoundationsRouteRoute: FoundationsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
