/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsButtonRouteImport } from './routes/components/button'
import { Route as ComponentsRailRouteImport } from './routes/components/rail'
import { Route as ComponentsSelectRouteImport } from './routes/components/select'
import { Route as FoundationsColorsRouteImport } from './routes/foundations/colors'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsButtonRoute = ComponentsButtonRouteImport.update({
  id: '/components/button',
  path: '/components/button',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRailRoute = ComponentsRailRouteImport.update({
  id: '/components/rail',
  path: '/components/rail',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSelectRoute = ComponentsSelectRouteImport.update({
  id: '/components/select',
  path: '/components/select',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationsColorsRoute = FoundationsColorsRouteImport.update({
  id: '/foundations/colors',
  path: '/foundations/colors',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/rail': typeof ComponentsRailRoute
  '/components/select': typeof ComponentsSelectRoute
  '/foundations/colors': typeof FoundationsColorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/rail': typeof ComponentsRailRoute
  '/components/select': typeof ComponentsSelectRoute
  '/foundations/colors': typeof FoundationsColorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/rail': typeof ComponentsRailRoute
  '/components/select': typeof ComponentsSelectRoute
  '/foundations/colors': typeof FoundationsColorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components/button'
    | '/components/rail'
    | '/components/select'
    | '/foundations/colors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components/button'
    | '/components/rail'
    | '/components/select'
    | '/foundations/colors'
  id:
    | '__root__'
    | '/'
    | '/components/button'
    | '/components/rail'
    | '/components/select'
    | '/foundations/colors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsButtonRoute: typeof ComponentsButtonRoute
  ComponentsRailRoute: typeof ComponentsRailRoute
  ComponentsSelectRoute: typeof ComponentsSelectRoute
  FoundationsColorsRoute: typeof FoundationsColorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/button': {
      id: '/components/button'
      path: '/components/button'
      fullPath: '/components/button'
      preLoaderRoute: typeof ComponentsButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/rail': {
      id: '/components/rail'
      path: '/components/rail'
      fullPath: '/components/rail'
      preLoaderRoute: typeof ComponentsRailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/select': {
      id: '/components/select'
      path: '/components/select'
      fullPath: '/components/select'
      preLoaderRoute: typeof ComponentsSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundations/colors': {
      id: '/foundations/colors'
      path: '/foundations/colors'
      fullPath: '/foundations/colors'
      preLoaderRoute: typeof FoundationsColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsButtonRoute: ComponentsButtonRoute,
  ComponentsRailRoute: ComponentsRailRoute,
  ComponentsSelectRoute: ComponentsSelectRoute,
  FoundationsColorsRoute: FoundationsColorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
