/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsBubbleRouteImport } from './routes/components/bubble'
import { Route as ComponentsButtonRouteImport } from './routes/components/button'
import { Route as ComponentsNestRouteImport } from './routes/components/nest'
import { Route as ComponentsSelectRouteImport } from './routes/components/select'
import { Route as FoundationsColorsRouteImport } from './routes/foundations/colors'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsBubbleRoute = ComponentsBubbleRouteImport.update({
  id: '/components/bubble',
  path: '/components/bubble',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsButtonRoute = ComponentsButtonRouteImport.update({
  id: '/components/button',
  path: '/components/button',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsNestRoute = ComponentsNestRouteImport.update({
  id: '/components/nest',
  path: '/components/nest',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSelectRoute = ComponentsSelectRouteImport.update({
  id: '/components/select',
  path: '/components/select',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationsColorsRoute = FoundationsColorsRouteImport.update({
  id: '/foundations/colors',
  path: '/foundations/colors',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components/bubble': typeof ComponentsBubbleRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/nest': typeof ComponentsNestRoute
  '/components/select': typeof ComponentsSelectRoute
  '/foundations/colors': typeof FoundationsColorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components/bubble': typeof ComponentsBubbleRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/nest': typeof ComponentsNestRoute
  '/components/select': typeof ComponentsSelectRoute
  '/foundations/colors': typeof FoundationsColorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components/bubble': typeof ComponentsBubbleRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/nest': typeof ComponentsNestRoute
  '/components/select': typeof ComponentsSelectRoute
  '/foundations/colors': typeof FoundationsColorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components/bubble'
    | '/components/button'
    | '/components/nest'
    | '/components/select'
    | '/foundations/colors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components/bubble'
    | '/components/button'
    | '/components/nest'
    | '/components/select'
    | '/foundations/colors'
  id:
    | '__root__'
    | '/'
    | '/components/bubble'
    | '/components/button'
    | '/components/nest'
    | '/components/select'
    | '/foundations/colors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsBubbleRoute: typeof ComponentsBubbleRoute
  ComponentsButtonRoute: typeof ComponentsButtonRoute
  ComponentsNestRoute: typeof ComponentsNestRoute
  ComponentsSelectRoute: typeof ComponentsSelectRoute
  FoundationsColorsRoute: typeof FoundationsColorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/bubble': {
      id: '/components/bubble'
      path: '/components/bubble'
      fullPath: '/components/bubble'
      preLoaderRoute: typeof ComponentsBubbleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/button': {
      id: '/components/button'
      path: '/components/button'
      fullPath: '/components/button'
      preLoaderRoute: typeof ComponentsButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/nest': {
      id: '/components/nest'
      path: '/components/nest'
      fullPath: '/components/nest'
      preLoaderRoute: typeof ComponentsNestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/select': {
      id: '/components/select'
      path: '/components/select'
      fullPath: '/components/select'
      preLoaderRoute: typeof ComponentsSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundations/colors': {
      id: '/foundations/colors'
      path: '/foundations/colors'
      fullPath: '/foundations/colors'
      preLoaderRoute: typeof FoundationsColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsBubbleRoute: ComponentsBubbleRoute,
  ComponentsButtonRoute: ComponentsButtonRoute,
  ComponentsNestRoute: ComponentsNestRoute,
  ComponentsSelectRoute: ComponentsSelectRoute,
  FoundationsColorsRoute: FoundationsColorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
